### ISSUE TITLE
Azure Object Anchors Model Conversion Error

### ISSUE THREAD

**Issue by Orz-NFU** [Azure/azure-object-anchors#16]
**Description**

I'm following docs and trying to convert a box (about 2.5m*3.5m*3.5m) but I keep getting errors
Asset conversion job failed with an error.
        ClientErrorDetails: The dimensions of the asset exceeded the physical dimension limit. This can be a sign of an improperly set scale for the asset when creating a job. Refer to the asset size guidelines before submitting an asset for conversion to ensure conformity, and ensure the provided scale corresponds to the uploaded asset: https://aka.ms/aoa/faq
        ServerErrorDetails:
Asset dimensions exceeded those allowed for an asset to be converted.

I follow this : https://docs.microsoft.com/en-us/azure/object-anchors/quickstarts/get-started-model-conversion

**Expected behavior**

Asset   : ***********
 Gravity : ***********
 Unit    : ***********
 Attempting to upload asset...
 Attempting to create asset conversion job...
 Successfully created asset conversion job. Job ID: ***********
 Waiting for job completion...

 Asset conversion job completed successfully.
 Attempting to download result as '***********'...
 Success!
**Screenshots**

![image](https://user-images.githubusercontent.com/76623686/148522406-85334afe-69b2-49bc-8c44-662a37065bf2.png)

model in 3ds Max
![image](https://user-images.githubusercontent.com/76623686/148522632-f8e28f95-f4d8-40da-9026-6952b7cb7ce2.png)

**Development information (please complete the following information)**

 - OS: [ Windows 10 ]
 - Development Platform\Version: [ Visual Studio 2019 ]
 - Azure Spatial Anchors SDK version: [ ]

**AR Device information (please complete the following information):**

 - Device: [HoloLens 2]
 - OS: [ ]

**Additional context**

**Comment by RamonArguelles** [comment]
Hi @Orz-NFU. Thanks for reaching out. Looking into our telemetry, we were able to find some traces about your failed conversion (thanks for posting the Job ID in your screenshot). The actual dimensions that AOA is calculating for your model are {"X":98.58281, "Y":107.57305, "Z":129.45291}. The reason for the discrepancy between the dimensions we are calculating, and the ones you might be seeing within 3DS Max, is likely because some model file types, like fbx, are capable of storing length units as internal metadata. Since AOA supports multiple file formats, it currently uses the lowest common denominator across all those file types. So it ignores any length units that might be stored as metadata in your model, and requires that you provide the proper length units in your request. In this case, your provided 'meters' as the length unit, so your model ended up measuring 98m x 107m x 129m, which exceeded AOA supported limits (any dimensions above 10m will produce this failure). If you were to resubmit using a length unit that allows all dimensions to be lower than 10m, for example centimeters, it should work.

In the future, we recommend that you use MeshLab for determining model dimensions. You can see the dimensions of 3D models in MeshLab via: Render -> Show Box Corners. You can use the model dimensions to determine the appropriate length units for AOA model conversion. 

Thanks!
