### ISSUE TITLE
Can not detected models while running the MRTK-AOA sample 

### ISSUE THREAD

**Issue by Xudarker** [Azure/azure-object-anchors#7]
**Description**

  I have followed the guidence of quick start at hololens and MRTK, successfully created an model, and got a return .ou file, 
and successfully build up app for hololens, but the problem is , hololens was unable to detecting model, the onscreen status message shows:
AOA status :paused(after start seraching,it will change to running)
Tracked:0;
Models:0;
querying:false

**Screenshots**
this is where i put the model:
![6$X22D%P7QPHQU}D~@AE5IS](https://user-images.githubusercontent.com/18206640/132326045-8cd24079-6e8e-4a09-b895-c54a43d3d5f4.png)

here is the model i used to dectect:
![11BC1C2652ED6D03943696F2C1986419](https://user-images.githubusercontent.com/18206640/132325397-c25fbd85-19a1-499d-b9a6-dfd6f6ae99cb.jpg)

length:42cm
width:30cm
height:50cm

**Development information (please complete the following information)**
unity:2019.4.17
AOA:0.13.0
windwos SDK:10.0.18362.0
hololens version:up to date

**Comment by craigktreasure** [comment]
Hmmm... Just to double check, did you place the bounding box around your object and then use the [hand menu](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_HandMenu.html) to start searching?
![image](https://user-images.githubusercontent.com/6309423/132378571-b37b4ac0-4a9f-4759-a082-4073ac43133c.png)

**Comment by Xudarker** [comment]
> Hmmm... Just to double check, did you place the bounding box around your object and then use the [hand menu](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_HandMenu.html) to start searching?
> ![image](https://user-images.githubusercontent.com/6309423/132378571-b37b4ac0-4a9f-4759-a082-4073ac43133c.png)

yes, I did that.

**Comment by Xudarker** [comment]
here is my unityplayer log file:
[UnityPlayer.log](https://github.com/Azure/azure-object-anchors/files/7125398/UnityPlayer.log)

**Comment by craigktreasure** [comment]
@Xudarker Your log file says "no objects to detect." which indicates that it isn't finding the .ou file in your 3D Objects folder. According to your screenshot, everything looks to be in the right place, so it certainly should find it. Are you perhaps running an older version of the sample app that doesn't support loading them from the 3D Objects folder?

An alternative to using the 3D Objects folder is to use the app's **Local State** folder. Bellow are some of our old instructions for uploading a model to the **Local State** folder using Windows Device Portal.

---

### Set up the Windows Device Portal

To connect to your HoloLens over WiFi, follow these steps:

1. First [Connect Your HoloLens to WiFi](/hololens/hololens-network).

2. Then get the IP address on the device under **Settings > Network & Internet > Wi-Fi > Advanced Options**.

3. From a web browser on your PC, go to `https://<YOUR_HOLOLENS_IP_ADDRESS>`. The browser will display the following message: "There's a problem with this website's security certificate". This message occurs because the certificate issued to the Device Portal is a self-signed certificate. You can ignore the certificate error and continue.

See [here](/windows/mixed-reality/using-the-windows-device-portal) for more info about setting up the Windows Device Portal.

### Upload your model

With your HoloLens connected to the Windows Device Portal, follow these steps to upload a model for the app to use:

In the Windows Device Portal, go to System > File explorer > LocalAppData. There, you should see your application on the list of apps.

![image](https://user-images.githubusercontent.com/6309423/132566012-69e3f1b5-d8b3-4c8e-b7f1-6ebad46bbc5b.png)

Open your application and click on the LocalState folder.

![image](https://user-images.githubusercontent.com/6309423/132566063-df178a69-9663-49ef-9dc5-421da47f370e.png)

Upload the model file to the LocalState folder.

![image](https://user-images.githubusercontent.com/6309423/132566249-8db71372-f348-4798-9b57-5750bb051096.png)

Launch the application from the HoloLens again. You can now detect objects matching the model.

**Comment by Xudarker** [comment]
@craigktreasure, thanks,it worked. the model has detected,but the accuracy looks like a little bit unlikeable,is there anyway i can improve it? 
  Besides,i want get the models information(positon,rotation,and properties) after detected while running, is there have any API that i can use for. thanks

**Comment by craigktreasure** [comment]
For your accuracy concern, what do you mean by "unlikeable"? Can you be more specific please? For large objects, the pose can be anywhere from 2 - 8 cm off (per our [FAQ](https://docs.microsoft.com/azure/object-anchors/faq)). I'd suggest having a look at our [Best Practices](https://docs.microsoft.com/azure/object-anchors/best-practices) to achieve the optimal pose accuracy. Another option, since you're using the MRTK app, is to enable **High Accuracy** mode in the **Tracker Settings**. This requires a bit more processing power, but can improve accuracy.

As for showing the 3D model, the sample app doesn't do that. That's more of a Unity exercise for the reader. Object Anchors will get you the location of the object and then you can load your 3D model and put it in the same location.

**Comment by Xudarker** [comment]
@craigktreasure  thanks for the answer, i think this may be caused by the small object, since you guys recommended 1-10meters object. this is what i detected show as below:
![20210910_000315_HoloLens](https://user-images.githubusercontent.com/18206640/132813824-2ba7070e-d3dd-4fdd-a958-57a87c57a251.jpg)

**Comment by craigktreasure** [comment]
@Xudarker Thanks. A picture is worth a thousand words. We think this could be a ghost artifact in the mesh after the object was moved. Here's a couple of things to try:
1. Per the [best practices](https://docs.microsoft.com/azure/object-anchors/best-practices), remove all Holograms using the **Settings** app -> **System** -> **Holograms** -> then select **Remove all holograms** and start with a fresh map.
2. With the latest ([September](https://github.com/Azure/azure-object-anchors/releases/tag/2021.9.1-preview)) version of the MRTK sample app with 0.14.0, we have a new preview feature that you can try out that should avoid this issue. It requires a bit more processing power when searching, but is quite powerful. With the project open in Unity, do the following:
    * Select the **AOASampleScene** scene and expand it in the hierarchy.
    * Select the **ObjectMixedRealityPlayspace** component.
    * In the Inspector, locate the **Object Tracker** script and change **Observation Mode** from **Ambient** to **Active**.
    * Save the scene (**File** -> **Save**).
    * Rebuild and redeploy the app.

**Comment by Xudarker** [comment]
@craigktreasure thanks for the answer, the accuracy did improve, but I have 2 different models saved in the LocalState folder, it seems when the tracked object shows, it shows with two objects together when I searching one model. I have seen some documents which said we can not detect more than one model at once, so if I want this work, I can only put one model in the folder, right? 

and the BoundingBox Rotation did not work, how can I activate it?

**Comment by craigktreasure** [comment]
Good question. It seems our [FAQ](https://docs.microsoft.com/azure/object-anchors/faq) has outdated information. I've submitted an update to clarify and update what we support here. Let me know if you see incorrect information elsewhere in our documentation, but the FAQ should be updated shortly with the correct information below:

> **Q: How many different models can Object Anchors detect at the same time?**
>
> **A:** We currently support detecting three models at a time to ensure the best user experience, but we don't enforce a
       limit.
>
> **Q: Can Object Anchors detect multiple instances of the same object model?**
>
> **A:** Yes, we support detecting up to three instances of the same model type to ensure the best user experience, but we
       don't enforce a limit. You can detect one object instance per search area. By calling
       `ObjectQuery.SearchAreas.Add`, you can add more search areas to a query to detect more instances. You can call
       `ObjectObserver.DetectAsync` with multiple queries to detect multiple models.

As for the bounding box, I don't believe rotating it has ever worked. It would be nice to be able to rotate it. I've filed a bug internally (36182369 for reference) to address that issue at some point. Thanks for the feedback.

**Comment by craigktreasure** [comment]
@Xudarker I believe we've resolved your original issue, so I'm going to close this issue for now. Thanks for all the feedback! If you encounter additional issues or have more feedback, please open a new issue. Thanks!
